# Используйте официальный образ Python 3.10 как базовый
FROM python:3.10

# Установите рабочую директорию
WORKDIR /app

# Установите зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Скопируйте код приложения в контейнер
COPY . .

# Сборка статических файлов
RUN python manage.py collectstatic --noinput

# Запустите команду для старта сервера в продакшн
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "main.wsgi:application"]
