version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: deployment/prod/Dockerfile.prod
    volumes:
      - ./../..:/app
      - certificates/etc/letsencrypt:/etc/letsencrypt
      - certificates/var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DJANGO_SETTINGS_MODULE>=main.settings.prod
    restart: always
