FROM python:3.10

WORKDIR /app

COPY requirements.prod.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ../../ /app

RUN python manage.py collectstatic --noinput

RUN apt-get update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*

COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080 80

CMD ["sh", "-c", "gunicorn --bind 127.0.0.1:8080 main.wsgi:application & nginx -g 'daemon off;'"]