version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./../..:/app
    ports:
      - "80:80"
    environment:
      - DJANGO_SETTINGS_MODULE=main.settings.prod