# Generated by Django 5.0.7 on 2024-08-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderCardsDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описании',
            },
        ),
        migrations.AlterModelOptions(
            name='slidercards',
            options={'verbose_name': 'Карточка слайдера', 'verbose_name_plural': 'Карточки слайдера'},
        ),
        migrations.RemoveField(
            model_name='slidercards',
            name='description',
        ),
        migrations.AlterField(
            model_name='products',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='products_logo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='slidercards',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='slider_cards_image', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='slidercards',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='slidercards',
            name='descriptions',
            field=models.ManyToManyField(blank=True, to='main.slidercardsdescriptions', verbose_name='Описании'),
        ),
    ]
