# Generated by Django 5.0.7 on 2024-08-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slidercardsdescriptions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='logo',
            field=models.ImageField(blank=True, help_text='150x150', null=True, upload_to='products_logo', verbose_name='Логотип'),
        ),
    ]
