# Generated by Django 5.0.7 on 2024-09-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mainsettings_telegram_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='site_favicon',
            field=models.ImageField(blank=True, help_text='ICO, PNG, GIF, JPEG, SVG', null=True, upload_to='', verbose_name='Иконка сайта'),
        ),
    ]
