# Generated by Django 5.0.7 on 2024-08-05 19:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_products_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=250, verbose_name='Название сайта')),
                ('site_description', models.CharField(max_length=250, verbose_name='Описание сайта')),
                ('index_color', colorfield.fields.ColorField(default='#91A323', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
