# Generated by Django 5.0.7 on 2024-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mainsettings_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsettings',
            name='telegram_group',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Телеграм айди группы'),
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='telegram_token',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Телеграм токен'),
        ),
        migrations.AlterField(
            model_name='products',
            name='logo',
            field=models.ImageField(blank=True, help_text='130x130', null=True, upload_to='products_logo', verbose_name='Логотип'),
        ),
    ]
